# Copyright 2024 The Kubermatic Kubernetes Platform contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{ if .Values.userMla.enable }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: mla
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: ArgoCD Project for all user cluster mla apps
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'
  destinations:
  - namespace: mla
    server: https://kubernetes.default.svc
---
apiVersion: v1
kind: Namespace
metadata:
  name: mla
{{ end }}

{{ if and .Values.userMla.enable .Values.userMla.minio.enable }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-mla-minio
  namespace: argocd
spec:
  project: mla
  sources:
  - repoURL: '{{ .Values.kkpRepoURL }}'
    path: {{ template "kkp.chart.pathprefix" . }}/charts/mla/minio
    targetRevision: {{ .Values.kkpVersion }}
    helm:
      releaseName: minio
      valueFiles:
        - values.yaml
        - $values/{{ template "argo-cd-apps.user-mla-values-file.path" . }}
  # This is your private repo where you have stored the values.yaml customizations which you used to provide to KKP installer. 
  - repoURL: '{{ .Values.repoURL }}'
    targetRevision: {{ template "git-tag-version" . }}
    path: {{ .Values.valuesPathPrefix }}
    ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mla
  {{- if .Values.userMla.minio.autoSync }}
  syncPolicy:
    automated: {}
  {{ end }}
{{ end }}

{{ if and .Values.userMla.enable .Values.userMla.secrets.enable }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-mla-secrets
  namespace: argocd
spec:
  project: mla
  sources:
  - repoURL: '{{ .Values.kkpRepoURL }}'
    path: {{ template "kkp.chart.pathprefix" . }}/charts/mla/mla-secrets
    targetRevision: {{ .Values.kkpVersion }}
    helm:
      valueFiles:
        - values.yaml
        - $values/{{ template "argo-cd-apps.user-mla-values-file.path" . }}
  # This is your private repo where you have stored the values.yaml customizations which you used to provide to KKP installer. 
  - repoURL: '{{ .Values.repoURL }}'
    targetRevision: {{ template "git-tag-version" . }}
    path: {{ .Values.valuesPathPrefix }}
    ref: values
    helm:
      # TODO: we should allow users to override releaseName. This will help in backward compatibility to existing helm charts AND not create duplicate resources
      # releaseName: mla-secrets
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mla
  {{- if .Values.userMla.secrets.autoSync }}
  syncPolicy:
    automated: {}
  {{ end }}
---
{{ end }}

{{ if and .Values.userMla.enable .Values.userMla.minioLifecycleMgr.enable }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-mla-minio-lifecycle-manager
  namespace: argocd
spec:
  project: mla
  sources:
  - repoURL: '{{ .Values.kkpRepoURL }}'
    path: {{ template "kkp.chart.pathprefix" . }}/charts/mla/minio-lifecycle-mgr
    targetRevision: {{ .Values.kkpVersion }}
    helm:
      valueFiles:
        - values.yaml
        - $values/{{ template "argo-cd-apps.user-mla-values-file.path" . }}
  # This is your private repo where you have stored the values.yaml customizations which you used to provide to KKP installer. 
  - repoURL: '{{ .Values.repoURL }}'
    targetRevision: {{ template "git-tag-version" . }}
    path: {{ .Values.valuesPathPrefix }}
    ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mla
  {{- if .Values.userMla.minioLifecycleMgr.autoSync }}
  syncPolicy:
    automated: {}
  {{ end }}
{{ end }}

{{ if and .Values.userMla.enable .Values.userMla.grafana.enable }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-mla-grafana
  namespace: argocd
spec:
  project: mla
  sources:
  - repoURL: '{{ .Values.kkpRepoURL }}'
    path: {{ template "kkp.chart.pathprefix" . }}/charts/mla/grafana
    targetRevision: {{ .Values.kkpVersion }}
    helm:
      releaseName: grafana
      valueFiles:
        - values.yaml
        - $values/{{ template "argo-cd-apps.user-mla-values-file.path" . }}
  # This is your private repo where you have stored the values.yaml customizations which you used to provide to KKP installer. 
  - repoURL: '{{ .Values.repoURL }}'
    targetRevision: {{ template "git-tag-version" . }}
    path: {{ .Values.valuesPathPrefix }}
    ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mla
  {{- if .Values.userMla.grafana.autoSync }}
  syncPolicy:
    automated: {}
  {{ end }}
{{ end }}

{{ if and .Values.userMla.enable .Values.userMla.consul.enable }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-mla-consul
  namespace: argocd
spec:
  project: mla
  sources:
  - repoURL: '{{ .Values.kkpRepoURL }}'
    path: {{ template "kkp.chart.pathprefix" . }}/charts/mla/consul
    targetRevision: {{ .Values.kkpVersion }}
    helm:
      releaseName: consul
      valueFiles:
        - values.yaml
        - $values/{{ template "argo-cd-apps.user-mla-values-file.path" . }}
  # This is your private repo where you have stored the values.yaml customizations which you used to provide to KKP installer. 
  - repoURL: '{{ .Values.repoURL }}'
    targetRevision: {{ template "git-tag-version" . }}
    path: {{ .Values.valuesPathPrefix }}
    ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mla
  {{- if .Values.userMla.consul.autoSync }}
  syncPolicy:
    automated: {}
  {{ end }}
{{ end }}

{{ if and .Values.userMla.enable .Values.userMla.alertmanagerProxy.enable }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-mla-alertmanager-proxy
  namespace: argocd
spec:
  project: mla
  sources:
  - repoURL: '{{ .Values.kkpRepoURL }}'
    path: {{ template "kkp.chart.pathprefix" . }}/charts/mla/alertmanager-proxy
    targetRevision: {{ .Values.kkpVersion }}
    helm:
      valueFiles:
        - values.yaml
        - $values/{{ template "argo-cd-apps.user-mla-values-file.path" . }}
  # This is your private repo where you have stored the values.yaml customizations which you used to provide to KKP installer. 
  - repoURL: '{{ .Values.repoURL }}'
    targetRevision: {{ template "git-tag-version" . }}
    path: {{ .Values.valuesPathPrefix }}
    ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mla
  {{- if .Values.userMla.alertmanagerProxy.autoSync }}
  syncPolicy:
    automated: {}
  {{ end }}
{{ end }}

{{ if and .Values.userMla.enable .Values.userMla.cortex.enable }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-mla-cortex
  namespace: argocd
spec:
  project: mla
  sources:
  - repoURL: '{{ .Values.kkpRepoURL }}'
    path: {{ template "kkp.chart.pathprefix" . }}/charts/mla/cortex
    targetRevision: {{ .Values.kkpVersion }}
    helm:
      releaseName: cortex
      valueFiles:
        - values.yaml
        - $values/{{ template "argo-cd-apps.user-mla-values-file.path" . }}
  # This is your private repo where you have stored the values.yaml customizations which you used to provide to KKP installer. 
  - repoURL: '{{ .Values.repoURL }}'
    targetRevision: {{ template "git-tag-version" . }}
    path: {{ .Values.valuesPathPrefix }}
    ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mla
  {{- if .Values.userMla.cortex.autoSync }}
  syncPolicy:
    automated: {}
  {{ end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cortex-runtime-config
  namespace: mla
data:
  runtime-config.yaml: 'overrides:'
{{ end }}

{{ if and .Values.userMla.enable .Values.userMla.lokiDistributed.enable }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-mla-loki-distributed
  namespace: argocd
spec:
  project: mla
  sources:
  - repoURL: '{{ .Values.kkpRepoURL }}'
    path: {{ template "kkp.chart.pathprefix" . }}/charts/mla/loki-distributed
    targetRevision: {{ .Values.kkpVersion }}
    helm:
      valueFiles:
        - values.yaml
        - $values/{{ template "argo-cd-apps.user-mla-values-file.path" . }}
  # This is your private repo where you have stored the values.yaml customizations which you used to provide to KKP installer. 
  - repoURL: '{{ .Values.repoURL }}'
    targetRevision: {{ template "git-tag-version" . }}
    path: {{ .Values.valuesPathPrefix }}
    ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mla
  {{- if .Values.userMla.lokiDistributed.autoSync }}
  syncPolicy:
    automated: {}
  {{ end }}
{{ end }}


{{ if and .Values.userMla.enable .Values.userMla.iapMla.enable }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-mla-iap
  namespace: argocd
spec:
  project: mla
  sources:
  - repoURL: '{{ .Values.kkpRepoURL }}'
    path: {{ template "kkp.chart.pathprefix" . }}/charts/iap
    targetRevision: {{ .Values.kkpVersion }}
    helm:
      valueFiles:
        - values.yaml
        - $values/{{ template "argo-cd-apps.user-mla-values-file.path" . }}
  # This is your private repo where you have stored the values.yaml customizations which you used to provide to KKP installer. 
  - repoURL: '{{ .Values.repoURL }}'
    targetRevision: {{ template "git-tag-version" . }}
    path: {{ .Values.valuesPathPrefix }}
    ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mla
  {{- if .Values.userMla.iapMla.autoSync }}
  syncPolicy:
    automated: {}
  {{ end }}
{{ end }}
