apiVersion: v1
name: promtail
version: 1.0.0
appVersion: v2.3.0
description: "Responsible for gathering logs and sending them to Loki"
keywords:
- kubermatic
- logging
- grafana
- loki
- promtail
home: https://grafana.com/loki
sources:
- https://github.com/grafana/loki
maintainers:
- name: The Kubermatic Kubernetes Platform contributors
  email: support@kubermatic.com

dependencies:
  - name: promtail
    version: "3.8.1"
    repository: "https://grafana.github.io/helm-charts"
