apiVersion: v2
name: cert-manager
description: A Helm chart for cert-manager
type: application
version: 0.1.0
appVersion: "2.18.0"
dependencies:
  - name: cert-manager
    version: 1.5.3
    repository: https://charts.jetstack.io