resources:
  - all.yaml
#  - secret-external.yaml
patches:
  - path: kustomize/patch.yaml

# On initial thoughts, replacements path should be avoided, as its too verbose to me. 
# But it might come handy to read things from rendered chart and use them in augmented charts.
# replacements:
# - source:
#     kind: Secret
#     name: minio
#     fieldPath: data.accesskey
#   targets:
#   - select:
#       name: s3-credentials-DELETEME
#       namespace: kube-system
#       kind: Secret
#     fieldPaths:
#     - data.ACCESS_KEY_ID
# - source:
#     kind: Secret
#     name: minio
#     fieldPath: data.secretkey
#   targets:
#   - select:
#       name: s3-credentials
#       namespace: kube-system
#       kind: Secret
#     fieldPaths:
#     - data.SECRET_ACCESS_KEY
